# Generated by Django 4.1.3 on 2022-11-22 23:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cv_basic', '0001_initial'),
        ('job_posting', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(default=datetime.datetime(2022, 11, 22, 18, 10, 54, 129751))),
                ('notes', models.TextField(blank=True, max_length=2500)),
                ('favorited', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('technical', 'Technical'), ('managerial', 'Managerial'), ('offer', 'Offer'), ('accepted', 'Accepted')], max_length=30)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='applications', to='user.user')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='applications', to='cv_basic.cvbasic')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='applications', to='job_posting.jobpost')),
            ],
        ),
    ]
