# Generated by Django 4.1.3 on 2022-11-23 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(default=datetime.datetime(2022, 11, 23, 11, 50, 26, 213832))),
                ('notes', models.TextField(blank=True, max_length=2500)),
                ('favorited', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('technical', 'Technical'), ('managerial', 'Managerial'), ('offer', 'Offer'), ('accepted', 'Accepted')], max_length=30)),
            ],
        ),
    ]
