# Generated by Django 4.1.3 on 2022-11-23 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cv_basic', '0001_initial'),
        ('application', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_posting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='applications', to='cv_basic.cvbasic'),
        ),
        migrations.AddField(
            model_name='application',
            name='job_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='applications', to='job_posting.jobpost'),
        ),
    ]
