# Generated by Django 4.1.3 on 2022-11-28 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_application_application_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 28, 11, 55, 59, 572373)),
        ),
    ]
