# Generated by Django 4.1.3 on 2022-12-04 17:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_application_application_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 4, 12, 58, 43, 425416)),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('technical', 'Technical'), ('managerial', 'Managerial'), ('offer', 'Offer'), ('accepted', 'Accepted')], default='applied', max_length=30),
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('notes', models.TextField(blank=True, max_length=2500)),
                ('datetime', models.DateTimeField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='application.application')),
            ],
        ),
    ]
