# Generated by Django 4.1.3 on 2022-12-05 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_application_application_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 4, 35, 47, 708091)),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('technical', 'Technical'), ('managerial', 'Managerial'), ('offer', 'Offer'), ('accepted', 'Accepted')], default='applied', max_length=30),
        ),
    ]
