# Generated by Django 4.1.3 on 2022-12-04 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_application_application_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Date',
            new_name='Saved_Date',
        ),
        migrations.AlterField(
            model_name='application',
            name='application_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 4, 13, 20, 13, 122369)),
        ),
    ]
