# Generated by Django 4.1.3 on 2022-11-22 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0002_alter_jobpost_date_created_alter_jobpost_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 12, 51, 23, 571623)),
        ),
    ]
