from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
# from . import models

STOP_WORDS = ("between",
              "twenty",
              "could",
              "once",
              "whenever",
              "nor",
              "ll",
              "describe",
              "meanwhile",
              "should",
              "'re",
              "become",
              "are",
              "sometime",
              "see",
              "even",
              "you'd",
              "'s",
              "y",
              "by",
              "beside",
              "de",
              "last",
              "together",
              "'ve",
              "and",
              "done",
              "for",
              "nine",
              "each",
              "shan",
              "interest",
              "their",
              "have",
              "must",
              "since",
              "rather",
              "before",
              "couldnt",
              "five",
              "nothing",
              "'ll",
              "were",
              "something",
              "many",
              "show",
              "seemed",
              "that",
              "aren",
              "'m",
              "thereby",
              "aren't",
              "thin",
              "part",
              "namely",
              "now",
              "they",
              "against",
              "eleven",
              "somehow",
              "it's",
              "with",
              "please",
              "we",
              "shouldn't",
              "becoming",
              "ourselves",
              "top",
              "one",
              "whereby",
              "how",
              "somewhere",
              "via",
              "haven't",
              "don",
              "ltd",
              "some",
              "anywhere",
              "system",
              "be",
              "sixty",
              "back",
              "whose",
              "ma",
              "four",
              "himself",
              "'d",
              "ie",
              "full",
              "ours",
              "already",
              "weren",
              "several",
              "'m",
              "whoever",
              "go",
              "others",
              "anyway",
              "won't",
              "you've",
              "thick",
              "due",
              "call",
              "couldn't",
              "won",
              "'s",
              "'d",
              "seems",
              "ve",
              "often",
              "another",
              "within",
              "you're",
              "her",
              "whither",
              "did",
              "no",
              "however",
              "whole",
              "will",
              "cannot",
              "per",
              "whereupon",
              "ten",
              "much",
              "do",
              "n't",
              "hasn",
              "perhaps",
              "them",
              "side",
              "hence",
              "its",
              "every",
              "'ve",
              "theirs",
              "being",
              "therefore",
              "while",
              "wasn",
              "wasn't",
              "detail",
              "during",
              "so",
              "fifteen",
              "doesn",
              "who",
              "well",
              "therein",
              "why",
              "anyhow",
              "into",
              "cant",
              "toward",
              "two",
              "myself",
              "'d",
              "sincere",
              "whereafter",
              "all",
              "mustn't",
              "etc",
              "fill",
              "those",
              "that'll",
              "as",
              "among",
              "at",
              "third",
              "you",
              "in",
              "find",
              "con",
              "below",
              "above",
              "t",
              "mustn",
              "six",
              "few",
              "because",
              "hereupon",
              "off",
              "bottom",
              "also",
              "has",
              "seeming",
              "than",
              "both",
              "wouldn't",
              "can",
              "doesn't",
              "does",
              "thereupon",
              "indeed",
              "any",
              "only",
              "wherein",
              "quite",
              "i",
              "under",
              "unless",
              "hers",
              "although",
              "always",
              "formerly",
              "these",
              "but",
              "what",
              "fire",
              "down",
              "nevertheless",
              "next",
              "too",
              "give",
              "us",
              "weren't",
              "should've",
              "nobody",
              "just",
              "serious",
              "becomes",
              "needn't",
              "further",
              "whereas",
              "this",
              "less",
              "where",
              "co",
              "front",
              "moreover",
              "hereby",
              "'ll",
              "wherever",
              "most",
              "thru",
              "hereafter",
              "first",
              "empty",
              "sometimes",
              "alone",
              "here",
              "more",
              "whom",
              "n't",
              "may",
              "mostly",
              "neither",
              "either",
              "beforehand",
              "him",
              "except",
              "didn",
              "former",
              "noone",
              "very",
              "bill",
              "found",
              "herein",
              "re",
              "amount",
              "she",
              "shan't",
              "might",
              "thereafter",
              "from",
              "around",
              "other",
              "amongst",
              "cry",
              "'s",
              "hasnt",
              "n't",
              "itself",
              "when",
              "s",
              "he",
              "it",
              "or",
              "make",
              "wouldn",
              "isn",
              "otherwise",
              "again",
              "hadn",
              "'re",
              "forty",
              "regarding",
              "keep",
              "though",
              "d",
              "'m",
              "yourselves",
              "elsewhere",
              "the",
              "really",
              "there",
              "latter",
              "onto",
              "ever",
              "towards",
              "an",
              "mightn't",
              "besides",
              "to",
              "still",
              "such",
              "whatever",
              "used",
              "she's",
              "until",
              "never",
              "through",
              "thus",
              "whether",
              "none",
              "behind",
              "o",
              "themselves",
              "using",
              "over",
              "didn't",
              "take",
              "own",
              "after",
              "throughout",
              "mill",
              "without",
              "else",
              "not",
              "thence",
              "which",
              "seem",
              "move",
              "herself",
              "his",
              "couldn",
              "you'll",
              "name",
              "eg",
              "say",
              "don't",
              "latterly",
              "yourself",
              "various",
              "hasn't",
              "m",
              "inc",
              "amoungst",
              "out",
              "upon",
              "mightn",
              "'re",
              "three",
              "anyone",
              "been",
              "if",
              "someone",
              "anything",
              "mine",
              "across",
              "would",
              "a",
              "having",
              "afterwards",
              "nowhere",
              "needn",
              "made",
              "ca",
              "on",
              "doing",
              "of",
              "'ve",
              "twelve",
              "same",
              "about",
              "shouldn",
              "am",
              "haven",
              "everyone",
              "almost",
              "un",
              "up",
              "everything",
              "get",
              "was",
              "ain",
              "least",
              "became",
              "yet",
              "put",
              "is",
              "fifty",
              "me",
              "isn't",
              "everywhere",
              "'ll",
              "my",
              "your",
              "hundred",
              "yours",
              "then",
              "beyond",
              "eight",
              "along",
              "enough",
              "had",
              "hadn't",
              "whence",
              "our"
              )


def get_text_matching_matrix(text):
    cv = CountVectorizer(stop_words=STOP_WORDS)
    count_matrix = cv.fit_transform(text)

    return count_matrix


def get_text_matching_score(text):
    cv = CountVectorizer(stop_words=STOP_WORDS)
    count_matrix = cv.fit_transform(text)

    # get the match percentage
    matchPercentage = cosine_similarity(count_matrix)[0][1] * 100
    matchPercentage = round(matchPercentage, 2)  # round to two decimal

    return {'count_matrix': count_matrix, 'matchPercentage': matchPercentage}


# resume_text = extract_text_from_docx(resume)
# job_description_text = extract_text_from_docx(job_description)

# text = [job_description_text, resume_text]

# matching_score = get_text_matching_score(text)

# print(matching_score['count_matrix'])
# print(matching_score['matchPercentage'])

# # Print the similarity scores
# print("\nSimilarity Scores:")
# print(cosine_similarity(matching_score['count_matrix']))

# print("Your resume matches about " +
#       str(matching_score['matchPercentage']) + "% of the job description.")

# db_skills = Skill.objects.all()
# required_skills = extract_skills(job_description_text, db_skills)
# matching_skills = get_matching_skills(resume_text, required_skills)
# matching_score = len(matching_skills)/len(required_skills)
# print(round(matching_score, 2))
