# Generated by Django 4.1.3 on 2022-11-22 17:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(default=datetime.datetime(2022, 11, 22, 12, 46, 47, 303767))),
                ('notes', models.TextField(blank=True, max_length=2500)),
                ('favorited', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('screening', 'Screening'), ('technical', 'Technical'), ('managerial', 'Managerial'), ('offer', 'Offer'), ('accepted', 'Accepted')], max_length=30)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='applications', to='cv.cv')),
            ],
        ),
    ]
