# Generated by Django 4.1.3 on 2022-11-22 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
        ('job_posting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='applications', to='job_posting.jobpost'),
        ),
    ]
