# Generated by Django 4.1.3 on 2022-11-22 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_application_applicant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 12, 55, 2, 139278)),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('technical', 'Technical'), ('managerial', 'Managerial'), ('offer', 'Offer'), ('accepted', 'Accepted')], max_length=30),
        ),
    ]
