# Generated by Django 4.1.3 on 2022-11-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
