# Generated by Django 4.1.3 on 2022-11-22 20:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('logo_url', models.URLField(blank=True)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 11, 22, 15, 20, 53, 144981))),
                ('remote_option', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('in-person', 'In-Person')], max_length=30)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
