# Generated by Django 4.1.3 on 2022-11-24 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 24, 0, 43, 4, 137449)),
        ),
    ]
