# Generated by Django 4.1.3 on 2022-11-25 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0003_alter_jobpost_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='company',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 25, 16, 28, 19, 410252)),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='logo_url',
            field=models.URLField(null=True),
        ),
    ]
