# Generated by Django 4.1.3 on 2022-12-04 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0005_alter_jobpost_company_alter_jobpost_date_created'),
        ('job_posting', '0007_alter_jobpost_date_created'),
    ]

    operations = [
    ]
