# Generated by Django 4.1.3 on 2022-12-04 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0008_merge_20221204_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 4, 12, 58, 43, 425416)),
        ),
    ]
