# Generated by Django 4.1.3 on 2022-12-07 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0016_skill_isskill_alter_jobpost_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='hash',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 15, 32, 22, 103429)),
        ),
    ]
