# Generated by Django 4.1.3 on 2022-12-07 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0017_jobpost_hash_alter_jobpost_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 15, 42, 19, 936925)),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='hash',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
