# Generated by Django 4.1.3 on 2022-11-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='summary',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
